apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-sc-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: "local-sc"